### ISSUE TITLE
Drive link 

### ISSUE THREAD

**Issue by MUHAMMEDZEYN** [hapless19/UAV2UAV-dataset#2]
I am actually interested in your work and I want to download the dataset. Can you please provide a google drive link for the project ? 

Tanks in advence

**Comment by hapless19** [comment]
Dear sir,

I will upload the dataset to google drive as soon as possible. Thanks.

Best regards,

Yong



---- Replied Message ----
| From | ***@***.***> |
| Date | 2/1/2023 17:01 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [hapless19/UAV2UAV-dataset] Drive link (Issue #2) |

I am actually interested in your work and I want to download the dataset. Can you please provide a google drive link for the project ?

Tanks in advence

**Comment by hapless19** [comment]
https://drive.google.com/drive/folders/1ZPmR2jIAetkypgrc6VurUXxqE7_LUxFK?usp=sharing

**Comment by MUHAMMEDZEYN** [comment]
Thanks for your help.
